# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "actionview"
gem "middleman"
gem "middleman-livereload"
# XXX: Does not work with middleman 4.x
# gem "middleman-deploy"
gem "middleman-compass"
gem "middleman-sprockets"

# For faster file watcher updates on Windows:
# gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

gem 'slim', '~>4.0'
gem "bigdecimal"
gem 'pry-byebug'
