require("spec/controllers/table_controller_spec.js")
require("spec/views/control_bar_spec.js")
require("spec/views/row_spec.js")
require("spec/views/row_list_spec.js")
require("spec/views/paginator_spec.js")
